services:

  db:
    container_name: dbprivatejet
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sofiaisabel
      - POSTGRES_DB=privatejet
    ports:
      - "5432:5432"